apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcu-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: dcu-dp-ds
  template:
    metadata:
      labels:
        name: dcu-dp-ds
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hygon.com/dcu
                operator: In
                values:
                - "true"
              - key: dcu-mode
                operator: NotIn
                values:
                - mig
              - key: dcu
                operator: NotIn
                values:
                - "on"
      containers:
      - image: image.sourcefind.cn:5000/dcu/admin/base/dcu-device-plugin:v2.3.0
        name: dcu-dp-cntr
        securityContext:
          privileged: true
        env:
          - name: "PULSE"
            value: "30"
          - name: "RESOURCE_REGISTER_STRATEGY"
            value: "mixed"
          - name: "LOG_THRESHOLD"
            value: "INFO"
          - name: "LOG_VERBOSE"
            value: "2"
          - name: "LOG_OUTPUT"
            value: "true"
          - name: "NODE_NAME"
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - name: dp
            mountPath: /var/lib/kubelet/device-plugins
          - name: dev
            mountPath: /dev
          - name: etc-vdev
            mountPath: /etc/vdev
            readOnly: true
          - name: hyhal
            mountPath: /opt/hyhal
            readOnly: true
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: etc-vdev
          hostPath:
            path: /etc/vdev
            type: DirectoryOrCreate
        - name: dev
          hostPath:
            path: /dev
        - name: hyhal
          hostPath:
            path: /opt/hyhal