apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcu-device-plugin-hami
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: dcu-dp-ds-hami
  template:
    metadata:
      labels:
        name: dcu-dp-ds-hami
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      nodeSelector:
        dcu: "on"
      serviceAccountName: dcu-device-plugin
      containers:
      - image: image.sourcefind.cn:5000/dcu/admin/base/dcu-device-plugin:v2.3.0
        name: dcu-dp-cntr
        securityContext:
          privileged: true
        env:
          - name: "PULSE"
            value: "30"
          - name: "RESOURCE_REGISTER_STRATEGY"
            value: "hami"
          - name: "LOG_THRESHOLD"
            value: "INFO"
          - name: "LOG_VERBOSE"
            value: "2"
          - name: "LOG_OUTPUT"
            value: "true"
          - name: "NODE_NAME"
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - name: dp
            mountPath: /var/lib/kubelet/device-plugins
          - name: dev
            mountPath: /dev
          - name: etc-vdev
            mountPath: /etc/vdev
          - name: hyhal
            mountPath: /opt/hyhal
            readOnly: true
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: etc-vdev
          hostPath:
            path: /etc/vdev
            type: DirectoryOrCreate
        - name: dev
          hostPath:
            path: /dev
        - name: hyhal
          hostPath:
            path: /opt/hyhal

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dcu-device-plugin
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - update
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - update
      - patch
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dcu-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dcu-device-plugin
subjects:
  - kind: ServiceAccount
    name: dcu-device-plugin
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcu-device-plugin
  namespace: kube-system