basic:
  controller_image_name: "kubegems/vc-controller-manager"
  scheduler_image_name: "kubegems/vc-scheduler"
  admission_image_name: "kubegems/vc-webhook-manager"
  agent_image_name: "kubegems/vc-agent"
  image_tag_version: v1.12.1
  image_registry: registry.cn-beijing.aliyuncs.com
  image_pull_policy: IfNotPresent